### ISSUE TITLE
[CORE] Rewrite internals from scratch

### ISSUE THREAD

**Issue by twlite** [yasumu-org/yasumu#140]
Initial prototype we built was __**a piece of shit**__. I want to rewrite `@yasumu/core` from scratch while providing excellent APIs to interact with the workspace. Things I want to include in this:

- [ ] Excellent, typesafe api to manipulate workspace data
- [ ] Robust reusable architecture (`@yasumu/core` allows plugging in Yasumu into any desired host environment)
- [ ] `@yasumu/schema` integration
- [ ] Importing workspaces or collections from alternative platforms
- [ ] Exporting workspace into sharable file
- [ ] Code generation support
- [ ] Performance improvements
- [ ] Extensions host environment

**Comment by vr-varad** [comment]
hey  @twlite is these issues or any issues open for contribution?
